import type { NextPage } from 'next'
import Head from 'next/head'

import { Button } from '../components/Button'

const Page: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Hello!</h1>
      </main>
      <Button />
    </div>
  )
}

export default Page
