# アクション名
name: CI

# ワークフローが実行されるトリガー
on: push

# Node 環境をセットアップ
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: yarn-install
        run: yarn
      - name: test
        run: yarn run jest
      - name: eslint
        run: yarn next lint
